######################################################################
# Automatically generated by qmake (3.0) Fri May 8 00:37:06 2015
######################################################################

TEMPLATE = app
TARGET = PBL
INCLUDEPATH += /usr/local/include/opencv \
               /usr/local/include
LIBS+= /usr/local/lib/libopencv_calib3d.so \ 
       /usr/local/lib/libopencv_core.so \
   /usr/local/lib/libopencv_features2d.so \
   /usr/local/lib/libopencv_flann.so \
   /usr/local/lib/libopencv_highgui.so \
   /usr/local/lib/libopencv_imgcodecs.so \
   /usr/local/lib/libopencv_imgproc.so \
   /usr/local/lib/libopencv_ml.so \
   /usr/local/lib/libopencv_objdetect.so \
   /usr/local/lib/libopencv_photo.so \
   /usr/local/lib/libopencv_shape.so \
   /usr/local/lib/libopencv_stitching.so \
   /usr/local/lib/libopencv_superres.so \
   /usr/local/lib/libopencv_ts.a \
   /usr/local/lib/libopencv_video.so \
   /usr/local/lib/libopencv_videoio.so \
   /usr/local/lib/libopencv_videostab.so  

QT+=widgets	  
HEADERS=ui_design.h
# Input
SOURCES += imagebar.cpp
